---

- name: Add clickhouse-operator chart repo
  kubernetes.core.helm_repository:
    name: altinity
    repo_url: "https://docs.altinity.com/clickhouse-operator/"
    repo_state: present

- name: Install clickhouse operator
  kubernetes.core.helm:
    release_name: altinity-clickhouse-operator
    release_namespace: default
    release_state: present
    chart_ref: altinity/altinity-clickhouse-operator
    state: present

- name: Create clickhouse installation
  vars:
    name: clickhouse
    namespace: default
  kubernetes.core.k8s:
    state: present
    template: clickhouse.yaml
