---
- hosts: all
  gather_facts: true
  become: yes
  roles:
  - users
  tags:
  - users

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/k3s_prereq
    - role: k3s/k3s_download
  tags:
  - addons

- hosts: master
  become: yes
  roles:
    - role: k3s/k3s_master
  tags:
  - addons

- hosts: node
  become: yes
  roles:
    - role: k3s/k3s_node
  tags:
  - addons

- hosts: master
  run_once: yes
  name: Reconcile addons
  tasks:
  - name: Update apt cache
    become: yes
    apt:
      update_cache: true
      cache_valid_time: 3600
  - name: Install python kubernetes library
    become: yes
    apt:
      update_cache: true
      cache_valid_time: 3600
      name:
        - python3-kubernetes
      state: present
  tags:
    - addons

- hosts: master
  run_once: yes
  roles:
  - role: clickhouse
  tags:
  - addons
