apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: default
spec:
  image: docker.io/bitnami/rabbitmq:3.10.18-debian-11-r0
  override: {}
  persistence:
    storage: 10Gi
  rabbitmq: {}
  replicas: 1
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 2Gi
  secretBackend: {}
  service:
    type: ClusterIP
  terminationGracePeriodSeconds: 604800
  tls: {}
