---
- name: Add minio helm repo
  kubernetes.core.helm_repository:
    repo_url: "https://operator.min.io/"
    repo_name: "minio"
    repo_state: present

- name: Install minio-operator
  kubernetes.core.helm:
    release_namespace: minio-operator
    release_name: minio-operator
    chart_ref: minio/operator
    state: present

- name: Install tenant
  kubernetes.core.helm:
    release_namespace: minio-tenant
    release_name: tenant
    chart_ref: minio/tenant
    release_values:
      secrets:
        # MinIO root user and password
        accessKey: ahhekohK9xuchoezeing
        secretKey: dangah9iiZ3yoghaiGhu

      tenant:
        certificate:
          requestAutoCert: false
        pools:
          ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
          ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
          ## Note that the operator does not support upgrading from standalone to distributed mode.
          - servers: 1
            ## custom name for the pool
            name: pool-0
            ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
            volumesPerServer: 4
            ## size specifies the capacity per volume
            size: 10Gi
            storageClassName: local-path
        log:
          disabled: true
          db:
            volumeClaimTemplate:
              spec:
                storageClassName: local-path
                size: 10Gi
        prometheus:
          disabled: true
        logging:
          quiet: false

      ingress:
        api:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            kubernetes.io/tls-acme: "true"
          tls:
            - hosts:
                - minio.skds-dev.dtlab.ranepa.ru
              secretName: minio-tls
          host: minio.skds-dev.dtlab.ranepa.ru
          path: /
          pathType: Prefix
        console:
          enabled: true
          ingressClassName: "nginx"
          labels: {}
          annotations:
            kubernetes.io/tls-acme: "true"
          tls:
            - hosts:
                - minio-console.skds-dev.dtlab.ranepa.ru
              secretName: minio-console-tls
          host: minio-console.skds-dev.dtlab.ranepa.ru
          path: /
          pathType: Prefix
    state: present
